Resources:
  # Cada user pool puede tener varios grupos
  # los grupos son conjuntos de usuarios que tienen permisos específicos
  UserPoolGroupUser:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: User
      UserPoolId: !Ref UserPool
      RoleArn: !GetAtt UserRole.Arn

  # en este caso, el grupo User tiene permisos para invocar cualquier lambda
  UserRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: UserRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cognito-idp.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: UserPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: '*'
