import LicenseHistoryEntity from '../../src/domain/entities/license/licenseHistory/licenseHistoryEntity';
import { LicenseHistoryActionsEnum } from '../../src/domain/entities/license/licenseHistory/enums/licenseHistoryEnums';
import { EntitiesEnum } from '../../src/domain/enums/entitiesEnum';
import outputTestResponse from '../utils/outputTestResponse';
// Generated by CodiumAI

describe('LicenseHistory', () => {
  // Successfully build LicenseHistoryEntityTableItemType with valid input
  it('should build LicenseHistoryEntityTableItemType when valid input is provided', () => {
    const input = {
      user_id: 'user124',
      license_id: 'license123',
      license_history_data: {
        action: LicenseHistoryActionsEnum.CREATE,
        action_changes: {
          license_type: 'licenseType',
          duration_in_Months: 12,
          user_id: 'user123',
        },
        action_user_pk: 'user123',
      },
    };

    const licenseHistory = new LicenseHistoryEntity();
    const result = licenseHistory.build(input);

    outputTestResponse({
      testName: 'licenseHistoryHappyPath',
      payload: result,
    });

    expect(result.pk).toBe(`LICENSE#${input.license_id}`);
    expect(result.sk).toBe(`LICENSE_HISTORY#${result.license_history_id}`);
    expect(result.type).toBe(EntitiesEnum.LICENSE_HISTORY);
    expect(result.user_id).toBe(input.user_id);
    expect(result.license_id).toBe(input.license_id);
    expect(result.license_history_data).toEqual(input.license_history_data);
    expect(result.creation_date).toBeDefined();
  });
});
